### ISSUE TITLE
Fix page flicker when going between pages

### ISSUE THREAD

**Issue by williamparry** [openlawnz/openlawnz-web#115]
There is a flicker when you navigate to another page.

**Comment by caionnx** [comment]
This one is basically reverting the code of the following merge: https://github.com/openlawnz/openlawnz-web/commit/40e09a4acd86b32c00d76fcefdb1aba0fe86ecaa

**Comment by opdev1004** [comment]
Flickering is just caused by animation.

I can update animation but it seems like the animation is only applied to where the flickering is happening.

So instead of reverting whole thing, I decided to change the animation to look like there's no animation.

I will commit and push my change but if you really want me to revert whole thing I can do that. But my current idea is maybe it is good to remain most of it for the future change.
