### ISSUE TITLE
Add more social images into the head

### ISSUE THREAD

**Issue by williamparry** [openlawnz/openlawnz-web#42]
For sharing on LinkedIn, Facebook etc. See https://developers.facebook.com/docs/sharing/webmasters/

**Comment by 300386357** [comment]
Can anyone tell me how to update this?

**Comment by caionnx** [comment]
@300386357 @Tzhong16 who wants to tackle this one? Basically is to include extra head tags to the website in order to produce something like [this](https://scontent.ffor8-1.fna.fbcdn.net/v/t39.2178-6/10956906_396737803821010_168799778_n.png?_nc_cat=107&_nc_ohc=WH2EKBoulIQAQlmwD1xsp91aSVQTcGh62yKb6atS3WLi0Zi90t8J5cIjw&_nc_ht=scontent.ffor8-1.fna&oh=86940d47ba2f7a1b0ca7a4c56ad71efc&oe=5E4779C0) in social media. 

Here is good explanation from facebook on how to do it: https://developers.facebook.com/docs/sharing/webmasters/

**Comment by caionnx** [comment]
Hi @Tzhong16 any impediments in this one? Thanks

**Comment by Tzhong16** [comment]
Hi @caionnx  I am working on it today, cheers

**Comment by 300386357** [comment]
@caionnx I submitted the social media image yesterday. Can you find out the image url so that @Tzhong16 can update the meta-data properties?

**Comment by caionnx** [comment]
Here it is https://github.com/openlawnz/openlawnz-web/pull/151 @300386357 @Tzhong16

**Comment by williamparry** [comment]
Any movement on this?

**Comment by Tzhong16** [comment]
Hey team, sorry about the delay. Just make a pull request, please check
